version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - cd frontend
      - echo "Building the app..."
      - npm run build
  
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build